export enum DiscoveryIntent {
  FRIENDSHIP = 'FRIENDSHIP',
  GAMING = 'GAMING',
  PROGRAMMING = 'PROGRAMMING',
  LANGUAGE_EXCHANGE = 'LANGUAGE_EXCHANGE',
  STUDY_PARTNER = 'STUDY_PARTNER',
  OTHER = 'OTHER',
}
