import { inject, injectable } from 'tsyringe';
import { IConnectionRepository } from '../interfaces/IConnectionRepository';
import { ConnectionRequest } from '../../domain/entities/ConnectionRequest';
import { ConnectionStatus } from '../../domain/enums/ConnectionStatus';

@injectable()
export class ConnectionService {
  constructor(
    @inject('IConnectionRepository') private readonly connectionRepository: IConnectionRepository
  ) {}

  public async sendRequest(senderId: string, receiverId: string, senderGuildId: string): Promise<ConnectionRequest> {
    const existing = await this.connectionRepository.findByUsers(senderId, receiverId);
    if (existing) {
      throw new Error('A connection or request already exists between these users.');
    }

    const request = new ConnectionRequest(
      '', // Generated by DB
      senderId,
      receiverId,
      ConnectionStatus.PENDING,
      new Date(),
      new Date(),
      senderGuildId
    );

    return this.connectionRepository.save(request);
  }

  public async skipUser(senderId: string, receiverId: string): Promise<ConnectionRequest> {
    const existing = await this.connectionRepository.findByUsers(senderId, receiverId);
    if (existing) return existing;

    const request = new ConnectionRequest(
      '',
      senderId,
      receiverId,
      ConnectionStatus.SKIPPED, // Store as skipped so they don't match again
      new Date(),
      new Date()
    );

    return this.connectionRepository.save(request);
  }

  public async getPendingRequests(discordId: string): Promise<ConnectionRequest[]> {
    return this.connectionRepository.findPendingRequests(discordId);
  }

  public async getRequestById(requestId: string): Promise<ConnectionRequest | null> {
    return this.connectionRepository.findById(requestId);
  }

  public async getRequestByChannelId(channelId: string): Promise<ConnectionRequest | null> {
    return this.connectionRepository.findByChannelId(channelId);
  }

  public async respondToRequest(requestId: string, accept: boolean, senderChannelId?: string, receiverChannelId?: string): Promise<ConnectionRequest> {
    const request = await this.connectionRepository.findById(requestId);
    if (!request) {
      throw new Error('Connection request not found.');
    }

    if (request.status !== ConnectionStatus.PENDING) {
      throw new Error('This request has already been processed.');
    }

    if (accept) {
      if (!senderChannelId || !receiverChannelId) throw new Error('Channel IDs are required when accepting a request.');
      request.accept(senderChannelId, receiverChannelId);
    } else {
      request.reject();
    }

    return this.connectionRepository.update(request);
  }

  public async handleReveal(channelId: string, discordId: string): Promise<{ bothRevealed: boolean; request: ConnectionRequest }> {
    const request = await this.connectionRepository.findByChannelId(channelId);
    if (!request) {
      throw new Error('This channel is not associated with an active connection.');
    }
    
    if (request.status === ConnectionStatus.REVEALED) {
      throw new Error('Identities are already revealed.');
    }

    const bothRevealed = request.reveal(discordId);
    const updated = await this.connectionRepository.update(request);
    
    return { bothRevealed, request: updated };
  }

  public async endChat(channelId: string): Promise<ConnectionRequest> {
    const request = await this.connectionRepository.findByChannelId(channelId);
    if (!request) {
      throw new Error('This channel is not associated with an active connection.');
    }

    request.end();
    return this.connectionRepository.update(request);
  }
}
