import { inject, injectable } from 'tsyringe';
import { IUserRepository } from '../interfaces/IUserRepository';
import { User } from '../../domain/entities/User';
import { UserProfile } from '../../domain/entities/Profile';

@injectable()
export class ProfileService {
  constructor(
    @inject('IUserRepository') private readonly userRepository: IUserRepository
  ) {}

  async getOrCreateUser(discordId: string): Promise<User> {
    let user = await this.userRepository.findByDiscordId(discordId);
    
    if (!user) {
      const defaultProfile: UserProfile = {
        languages: [],
        interests: [],
        hobbies: [],
        games: [],
        activityTime: { startHour: 0, endHour: 23 },
        lookingFor: [],
      };
      
      const newUser = new User(
        '', // Will be generated by DB
        discordId,
        false, // Not discoverable until profile is complete
        defaultProfile,
        new Date(),
        new Date()
      );
      
      user = await this.userRepository.save(newUser);
    }
    
    return user;
  }

  async updateProfile(discordId: string, profileUpdates: Partial<UserProfile>): Promise<User> {
    const user = await this.userRepository.findByDiscordId(discordId);
    if (!user) {
      throw new Error('User not found');
    }

    user.updateProfile(profileUpdates);
    return this.userRepository.update(user);
  }

  async toggleVisibility(discordId: string, isDiscoverable: boolean): Promise<User> {
    const user = await this.getOrCreateUser(discordId);

    if (isDiscoverable && user.profile.lookingFor.length === 0) {
      throw new Error('You must set what you are "Looking For" before becoming discoverable.');
    }

    user.toggleDiscoverability(isDiscoverable);
    return this.userRepository.update(user);
  }
}
